swagger: "2.0"
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
host: [HOST_NAME]
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: [https://HOST_NAME]
  protocol: h2
paths:
  /hello:
    get:
      operationId: hello
      responses:
        '200':
          description: A successful response
          schema:
            type: string